version: '3.1'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: airlineapp
      MYSQL_USER: airline-admin
      MYSQL_PASSWORD: passwd
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
